"""
Real testcases extracted from CodinGame using Selenium
Generated by the improved scraper with both input and output data
"""

TEST_INPUTS = {'test_1': '2.5 4 15 473', 'test_2': '2 2.1 17 200', 'test_3': '2.1 10.5 6 550', 'test_4': '3 3.25 24 700', 'test_5': '7 9.25 18.5 3300', 'test_6': '1 3 4 25'}
TEST_OUTPUTS = {'test_1': '14.3', 'test_2': '15.2', 'test_3': '5.0', 'test_4': '22.9', 'test_5': '16.4', 'test_6': '2.7'}


def print_test_summary():
    """Print a summary of all testcases."""
    print("Available testcases:")
    for test_name in sorted(TEST_INPUTS.keys()):
        input_data = TEST_INPUTS[test_name]
        output_data = TEST_OUTPUTS[test_name]
        if input_data:
            print(f"  {test_name}: Input {len(input_data)} chars, Output {len(output_data)} chars")
        else:
            print(f"  {test_name}: No data")


if __name__ == "__main__":
    print_test_summary()
