"""
Real testcases extracted from CodinGame using Selenium
Generated by the improved scraper with both input and output data
"""

TEST_INPUTS = {
    "test_1": "Authority Bills Capture",
    "test_2": "Harry Edward London London Orange",
    "test_3": "Washington Oslo Roma Liverpool Denmark",
    "test_4": "Romeo Echo Golf Romeo Echo Sierra Sierra",
    "test_5": "Tripoli Havana Edison Quebec Uppsala Italia Casablanca Kilogramme",
    "test_6": "Bravo Romeo Oscar Whiskey November Foxtrot Oscar X-ray",
    "test_7": "Lima Alfa Zulu Yankee Delta Oscar Golf",
    "test_8": "Tommy Harry Edward Queenie Uncle Ink Charlie King",
    "test_9": "Tango Hotel Echo Quebec Uniform India Charlie Kilo",
    "test_10": "Charlie Charlie Delta",
    "test_11": "Charlie Charlie Duff",
    "test_12": "Quebec Quebec Roma",
    "test_13": "Quebec Quebec Romeo Sierra",
    "test_14": "Charlie Quebec Charlie Quebec",
}
TEST_OUTPUTS = {
    "test_1": "Apples Butter Charlie",
    "test_2": "Havana Edison Liverpool Liverpool Oslo",
    "test_3": "Whiskey Oscar Romeo Lima Delta",
    "test_4": "Remarks Englishmen Galloping Remarks Englishmen Support Support",
    "test_5": "Tango Hotel Echo Quebec Uniform India Charlie Kilo",
    "test_6": "Bills Remarks Owners When Never Fractious Owners Xpeditiously",
    "test_7": "Loose Authority Zigzag Your Destroy Owners Galloping",
    "test_8": "Tripoli Havana Edison Quebec Uppsala Italia Casablanca Kilogramme",
    "test_9": "The High Englishmen Queen Unless Invariably Capture Knights",
    "test_10": "Capture Capture Destroy",
    "test_11": "Casablanca Casablanca Denmark",
    "test_12": "Quebec Quebec Romeo",
    "test_13": "Queen Queen Remarks Support",
    "test_14": "Capture Queen Capture Queen",
}


def print_test_summary():
    """Print a summary of all testcases."""
    print("Available testcases:")
    for test_name in sorted(TEST_INPUTS.keys()):
        input_data = TEST_INPUTS[test_name]
        output_data = TEST_OUTPUTS[test_name]
        if input_data:
            print(f"  {test_name}: Input {len(input_data)} chars, Output {len(output_data)} chars")
        else:
            print(f"  {test_name}: No data")


if __name__ == "__main__":
    print_test_summary()
